Repository TechneAi20231005/TechTicket, pull requests merged in 2024-07, with the labels that each got.

#304 Feature/add redux to sidebar
  src/components/Common/Sidebar.jsx
  src/redux/slices/Sidebar/index.js
Labels: Improvement, Resolved, question

#303 Bill checking master alignment issues and dropdown boarder issue reso…
  src/assetsNew/css/my-task.style.min.css
  src/screens/BillChecking/BillPayments/BillPayments.jsx
  src/screens/Settings/CustomerMapping/CreateCustomerMappingComponent.jsx
  src/screens/TicketManagement/CreateTicketComponent.jsx
Labels: bug, Improvement, Resolved

#305 Feature/testcases/filter/apiintegration
  src/redux/services/testCases/testCaseReview/index.js
  src/redux/slices/testCases/downloadFormatFile/index.js
  src/redux/slices/testCases/testCaseReview/index.js
  src/screens/TestCases/Modal/CustomFilterModal.jsx
  src/screens/TestCases/TestCaseReview/TestCaseReviewComponent.jsx
  src/screens/TestCases/TestCaseReview/TestCaseReviewDetails.jsx
  src/screens/TestCases/TestDraft/DownloadFormatFileModal.jsx
  src/screens/TestCases/TestDraft/EditTestCaseModal.jsx
  src/screens/TestCases/TestDraft/ReviewedTestDraftComponent.jsx
  src/screens/TestCases/TestDraft/ReviewedTestDraftDetails.jsx
  src/screens/TestCases/TestDraft/TestCaseHistoryComponent.jsx
  src/screens/TestCases/TestDraft/TestDraftComponent.jsx
  src/screens/TestCases/TestDraft/TestDraftDetails.jsx
  src/screens/TicketManagement/CreateTicketComponent.jsx
Labels: Improvement
