Repository TechneAi20231005/TechTicket, pull requests merged in 2024-06, with the labels that each got.

#204 Feature/ticket search
  src/screens/TicketManagement/MyTicketComponent.jsx
Labels: bug, Improvement, Resolved

#170 Feature/skeleton loader
  src/assetsNew/css/my-task.style.min.css
  src/components/custom/loader/CardLoadingSkeleton.jsx
  src/screens/ConsolidatedView/ConsolidatedSlice.js
  src/screens/ConsolidatedView/ConsolidatedView.jsx
  src/screens/ConsolidatedView/CurrentClientProject.jsx
  src/screens/ProjectManagement/ModuleMaster/ModuleComponent.jsx
  src/screens/ProjectManagement/ProjectMaster/ProjectComponent.jsx
  src/screens/ProjectManagement/SubModuleMaster/SubModuleComponent.jsx
Labels: bug, Resolved, dev test needed

#215 feature/test-cases/api-integration
  src/App.css
  src/App.js
  src/components/Utilities/Table/ExportDataFile.js
  src/redux/services/testCases/downloadFormatFile/index.js
  src/redux/services/testCases/testBank/index.js
  src/redux/services/testCases/testCaseReview/index.js
  src/redux/slices/testCases/downloadFormatFile/index.js
  src/redux/slices/testCases/testBank/index.js
  src/redux/slices/testCases/testCaseReview/index.js
  src/redux/store/store.js
  src/screens/Dashboard/DashbordSlice.js
  src/screens/MainIndex.js
  src/screens/TestCases/FunctionMaster/FunctionMasterComponent.js
  src/screens/TestCases/ReviewCommentMaster/ReviewCommentMasterComponent.js
  src/screens/TestCases/TestBank/TestBankComponent.js
  src/screens/TestCases/TestCaseReview/TestCaseReviewComponent.js
  src/screens/TestCases/TestCaseReview/TestCaseReviewDetails.js
  src/screens/TestCases/TestDraft/DownloadFormatFileModal.js
  src/screens/TestCases/TestDraft/EditTestCaseModal.js
  src/screens/TestCases/TestDraft/ReviewedTestDraftComponent.js
  src/screens/TestCases/TestDraft/ReviewedTestDraftDetails.js
  src/screens/TestCases/TestDraft/TestDraftComponent.js
  src/screens/TestCases/TestDraft/TestDraftDetails.js
  src/screens/TestCases/TestDraft/Validation/DownloadFormatFile.js
  src/screens/TestCases/TestDraft/Validation/EditTestCase.js
  src/screens/TestCases/TestingGroupMaster/TestingGroupMasterComponent.js
  src/screens/TestCases/TestingTypeMaster/TestingTypeMasterComponent.js
Labels: Improvement, question

#281 Feature/custom page header
  src/assetsNew/css/my-task.style.min.css
  src/components/Common/SearchBoxHeader .jsx
  src/screens/BillChecking/AuthorityMapping/AuthorityMapping.jsx
  src/screens/BillChecking/BillCheckingTransactions/BillCheckingTransaction.jsx
  src/screens/BillChecking/Masters/BillTypeMaster.jsx
  src/screens/BillChecking/Masters/PaymentTemplateMaster.jsx
  src/screens/BillChecking/Masters/VendorMaster.jsx
  src/screens/Masters/CityMaster/CityComponent.jsx
  src/screens/Masters/CountryMaster/CountryComponent.jsx
  src/screens/Masters/CustomerMaster/CustomerComponent.jsx
  src/screens/Masters/CustomerTypeMaster/CustomerTypeComponent.jsx
  src/screens/Masters/DepartmentMaster/DepartmentComponent.jsx
  src/screens/Masters/DepartmentMaster/DepartmentMasterAction.js
  src/screens/Masters/DepartmentMaster/DepartmentMasterSlice.js
  src/screens/Masters/DesignationMaster/DesignationAction.js
  src/screens/Masters/DesignationMaster/DesignationComponent.jsx
  src/screens/Masters/DesignationMaster/DesignationSlice.js
  src/screens/Masters/DynamicFormDropdown/DynamicFormDropdownComponent.jsx
  src/screens/Masters/DynamicFormMaster/CreateDynamicForm.jsx
  src/screens/Masters/DynamicFormMaster/DynamicFormComponent.jsx
  src/screens/Masters/DynamicFormMaster/EditDynamicForm.jsx
  src/screens/Masters/QueryTypeMaster/QueryTypeComponent.jsx
  src/screens/Masters/RoleMaster/RoleComponent.jsx
  src/screens/Masters/StateMaster/StateComponent.jsx
  src/screens/Masters/StatusMaster/StatusComponent.jsx
  src/screens/Masters/TaskAndTicketTypeMaster/TaskAndTicketTypeMaster.js
  src/screens/Masters/TemplateMaster/TemplateComponent.jsx
  src/screens/Masters/TestingTypeMaster/TestingTypeComponent.jsx
  src/screens/Masters/UserMaster/CreateUserComponent.jsx
  src/screens/Masters/UserMaster/UserComponent.jsx
  src/screens/ProjectManagement/ModuleMaster/ModuleComponent.jsx
  src/screens/ProjectManagement/ProjectMaster/ProjectComponent.jsx
  src/screens/ProjectManagement/SubModuleMaster/SubModuleComponent.jsx
  src/screens/Settings/CustomerMapping/CustomerMappingComponent.jsx
  src/screens/Settings/GeneralSettings/GeneralSettingsComponent.jsx
  src/screens/Settings/SettingSlice.js
Labels: enhancement, Improvement

#271 Feature/testcases/filter/apiintegration
  src/redux/services/testCases/downloadFormatFile/index.js
  src/redux/services/testCases/testCaseReview/index.js
  src/redux/slices/testCases/downloadFormatFile/index.js
  src/redux/slices/testCases/functionMaster/index.js
  src/redux/slices/testCases/reviewCommentMaster/index.js
  src/redux/slices/testCases/testBank/index.js
  src/redux/slices/testCases/testCaseReview/index.js
  src/screens/MainIndex.js
  src/screens/TestCases/FunctionMaster/AddEditFunctionMaster.jsx
  src/screens/TestCases/FunctionMaster/FunctionMasterComponent.jsx
  src/screens/TestCases/Modal/CustomFilterModal.js
  src/screens/TestCases/Modal/CustomFilterModal.jsx
  src/screens/TestCases/Modal/CustomFilterStyle.css
  src/screens/TestCases/ReviewCommentMaster/ReviewCommentMasterComponent.jsx
  src/screens/TestCases/ReviewCommentMaster/Validation/AddEditReviewCommentMaster.jsx
  src/screens/TestCases/TestBank/TestBankComponent.jsx
  src/screens/TestCases/TestCaseReview/TestCaseReviewComponent.js
  src/screens/TestCases/TestCaseReview/TestCaseReviewComponent.jsx
  src/screens/TestCases/TestCaseReview/TestCaseReviewDetails.js
  src/screens/TestCases/TestCaseReview/TestCaseReviewDetails.jsx
  src/screens/TestCases/TestDraft/DownloadFormatFileModal.jsx
  src/screens/TestCases/TestDraft/EditTestCaseModal.jsx
  src/screens/TestCases/TestDraft/ReviewedTestDraftComponent.js
  src/screens/TestCases/TestDraft/ReviewedTestDraftComponent.jsx
  src/screens/TestCases/TestDraft/ReviewedTestDraftDetails.js
  src/screens/TestCases/TestDraft/ReviewedTestDraftDetails.jsx
  src/screens/TestCases/TestDraft/TestCaseHistoryComponent.js
  src/screens/TestCases/TestDraft/TestCaseHistoryComponent.jsx
  src/screens/TestCases/TestDraft/TestDraftComponent.jsx
  src/screens/TestCases/TestDraft/TestDraftDetails.js
  src/screens/TestCases/TestDraft/TestDraftDetails.jsx
  src/screens/TestCases/TestDraft/Validation/EditTestCase.js
  src/screens/TestCases/TestingGroupMaster/AddTestingGroupModal.jsx
  src/screens/TestCases/TestingGroupMaster/TestingGroupMasterComponent.jsx
  src/screens/TestCases/TestingTypeMaster/AddTestingTypeModal.jsx
  src/screens/TestCases/TestingTypeMaster/TestingTypeMasterComponent.jsx
Labels: bug, Improvement, Resolved

#272 Integrate Redux for managing sidebar state
  src/components/Common/Sidebar.js
  src/components/Common/Sidebar.jsx
  src/redux/services/Sidebar/index.js
  src/redux/slices/Sidebar/index.js
  src/redux/store/store.js
Labels: enhancement, Improvement, Resolved, question

#270 increase the scrolling height
  src/screens/TicketManagement/MyTicketComponent.jsx
Labels: bug, Resolved, dev test needed

#278 bugfix/time-regularization
  src/screens/Dashboard/Dashboard.js
  src/services/NotificationService/NotificationService.js
Labels: enhancement, Improvement, Resolved
